# Generated by Django 4.1.7 on 2023-05-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambit',
            fields=[
                ('codi', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='nom àmbit')),
            ],
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('codi', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='nom departament')),
            ],
        ),
        migrations.CreateModel(
            name='Licitacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacio', models.TextField(null=True)),
                ('objecte_contracte', models.TextField(null=True)),
                ('pressupost', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('valor_estimat_contracte', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('duracio_contracte', models.IntegerField(null=True)),
                ('data_inici', models.DateField(null=True)),
                ('data_fi', models.DateField(null=True)),
                ('termini_presentacio_ofertes', models.DateTimeField(null=True)),
                ('data_publicacio_anunci', models.DateTimeField(null=True)),
                ('data_publicacio_adjudicacio', models.DateTimeField(null=True)),
                ('import_adjudicacio_sense_iva', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('import_adjudicacio_amb_iva', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('ofertes_rebudes', models.IntegerField(null=True)),
                ('resultat', models.CharField(max_length=50, null=True)),
                ('data_adjudicacio_contracte', models.DateField(null=True)),
                ('data_formalitzacio_contracte', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaFavorits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacions', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Localitzacio',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('longitud', models.DecimalField(decimal_places=16, max_digits=22, null=True)),
                ('latitud', models.DecimalField(decimal_places=16, max_digits=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('codi', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='nom organ')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceAmbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
