# Generated by Django 4.1.7 on 2023-05-09 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licitacions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listafavorits',
            name='licitacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorits', to='licitacions.licitacio'),
        ),
        migrations.AddField(
            model_name='listafavorits',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licitacio',
            name='lloc_execucio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacio', to='licitacions.localitzacio'),
        ),
        migrations.AddField(
            model_name='licitacio',
            name='tipus_contracte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacio', to='licitacions.tipuscontracte'),
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(fields=('user', 'tipus_contracte'), name='unique_preference'),
        ),
        migrations.AddConstraint(
            model_name='listafavorits',
            constraint=models.UniqueConstraint(fields=('user', 'licitacio'), name='unique_favorits'),
        ),
        migrations.AddField(
            model_name='licitaciopublica',
            name='ambit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacio_publica', to='licitacions.ambit'),
        ),
        migrations.AddField(
            model_name='licitaciopublica',
            name='departament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacio_publica', to='licitacions.departament'),
        ),
        migrations.AddField(
            model_name='licitaciopublica',
            name='organ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacio_publica', to='licitacions.organ'),
        ),
        migrations.AddField(
            model_name='licitacioprivada',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licitacio_privada', to=settings.AUTH_USER_MODEL),
        ),
    ]
