# Generated by Django 4.1.7 on 2023-05-07 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licitacions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='empresa',
        ),
        migrations.AddField(
            model_name='licitacioprivada',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licitacio_privada', to=settings.AUTH_USER_MODEL),
        ),
    ]
