# Generated by Django 4.1.7 on 2023-03-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitaciopublica',
            name='data_fi',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='licitaciopublica',
            name='data_inici',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='licitaciopublica',
            name='duracio_contracte',
            field=models.IntegerField(null=True),
        ),
    ]
