# Generated by Django 4.1.7 on 2023-05-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacio',
            name='num_favorits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='licitacio',
            name='visualitzacions',
            field=models.IntegerField(null=True),
        ),
    ]
