# Generated by Django 4.1.7 on 2023-05-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listafavorits',
            name='notificacions',
            field=models.BooleanField(default=False),
        ),
    ]
