# Generated by Django 4.1.7 on 2023-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacio',
            name='pressupost',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
