# Generated by Django 4.1.7 on 2023-03-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localitzacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('longitud', models.DecimalField(decimal_places=16, max_digits=22)),
                ('latitud', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
        ),
        migrations.AlterField(
            model_name='licitacio',
            name='procediment',
            field=models.CharField(choices=[('Obert', 'Obert'), ('Contracte menor', 'Contracte menor'), ('Negociat sense publicitat', 'Negociat sense publicitat'), ('Contracte basat en acord marc', 'Contracte basat en acord marc'), ('Altres procediments segons instruccions internes', 'Altres procediments segons instruccions internes'), ('Restringit', 'Restringit'), ('Específic de Sistema Dinàmic de Adquisició', 'Específic de Sistema Dinàmic de Adquisició'), ('Concurs de projectes', 'Concurs de projectes'), ('Contracte derivat de acord marc', 'Contracte derivat de acord marc'), ('Licitació amb negociació', 'Licitació amb negociació'), ('Negociat amb publicitat', 'Negociat amb publicitat')], max_length=150),
        ),
    ]
