# Generated by Django 4.1.7 on 2023-04-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0002_licitaciopublica_data_fi_licitaciopublica_data_inici_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='codi_cpv',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='data_adjudicacio_contracte',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='data_formalitzacio_contracte',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='data_publicacio_adjudicacio',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='data_publicacio_anunci',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='denominacio',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='duracio_contracte',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='fase_publicacio',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='id',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='import_adjudicacio_amb_iva',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='import_adjudicacio_sense_iva',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='lloc_execucio',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='objecte_contracte',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='ofertes_rebudes',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='pressupost',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='procediment',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='resultat',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='termini_presentacio_ofertes',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='tipus_contracte',
        ),
        migrations.RemoveField(
            model_name='licitacioprivada',
            name='valor_estimat_contracte',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='data_adjudicacio_contracte',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='data_fi',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='data_formalitzacio_contracte',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='data_inici',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='data_publicacio_adjudicacio',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='data_publicacio_anunci',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='denominacio',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='duracio_contracte',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='id',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='import_adjudicacio_amb_iva',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='import_adjudicacio_sense_iva',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='lloc_execucio',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='objecte_contracte',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='ofertes_rebudes',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='pressupost',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='resultat',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='termini_presentacio_ofertes',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='tipus_contracte',
        ),
        migrations.RemoveField(
            model_name='licitaciopublica',
            name='valor_estimat_contracte',
        ),
        migrations.AddField(
            model_name='licitacioprivada',
            name='empresa',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Licitacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacio', models.TextField(null=True)),
                ('objecte_contracte', models.TextField(null=True)),
                ('pressupost', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('valor_estimat_contracte', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('duracio_contracte', models.IntegerField(null=True)),
                ('data_inici', models.DateField(null=True)),
                ('data_fi', models.DateField(null=True)),
                ('termini_presentacio_ofertes', models.DateTimeField(null=True)),
                ('data_publicacio_anunci', models.DateTimeField(null=True)),
                ('data_publicacio_adjudicacio', models.DateTimeField(null=True)),
                ('import_adjudicacio_sense_iva', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('import_adjudicacio_amb_iva', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('ofertes_rebudes', models.IntegerField(null=True)),
                ('resultat', models.CharField(max_length=50, null=True)),
                ('data_adjudicacio_contracte', models.DateField(null=True)),
                ('data_formalitzacio_contracte', models.DateField(null=True)),
                ('lloc_execucio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacio', to='licitacions.localitzacio')),
                ('tipus_contracte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacio', to='licitacions.tipuscontracte')),
            ],
        ),
        migrations.AddField(
            model_name='licitacioprivada',
            name='licitacio_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='licitacions.licitacio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licitaciopublica',
            name='licitacio_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='licitacions.licitacio'),
            preserve_default=False,
        ),
    ]
