# Generated by Django 4.1.7 on 2023-05-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0002_listafavorits_notificacions'),
        ('licitacions', '0002_remove_licitacioprivada_empresa_and_more'),
    ]

    operations = [
    ]
