# Generated by Django 4.1.7 on 2023-05-10 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('licitacions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceTipusLicitacio',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preference_tipus_licitacio', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('privades', models.BooleanField(default=False)),
                ('publiques', models.BooleanField(default=False)),
            ],
        ),
    ]
