# Generated by Django 4.1.7 on 2023-04-30 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licitacions', '0003_remove_licitacioprivada_codi_cpv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaFavorits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licitacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorits', to='licitacions.licitacio')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='listafavorits',
            constraint=models.UniqueConstraint(fields=('user', 'licitacio'), name='unique_favorits'),
        ),
    ]
