# Generated by Django 4.1.7 on 2023-06-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0003_alter_licitacio_ofertes_rebudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='estat',
            field=models.TextField(choices=[('Rebutjada', 'Rebutjada'), ('En procés', 'En procés'), ('Acceptada', 'Acceptada')], default='En procés', max_length=150, null=True),
        ),
    ]
