# Generated by Django 4.1.7 on 2023-03-23 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0003_ambit_departament_licitacioprivada_licitaciopublica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacioprivada',
            name='lloc_execucio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacio_privada', to='licitacions.localitzacio'),
        ),
        migrations.AddField(
            model_name='licitaciopublica',
            name='lloc_execucio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacio_publica', to='licitacions.localitzacio'),
        ),
    ]
