# Generated by Django 4.1.7 on 2023-05-09 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20230508_0816'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licitacions', '0003_merge_20230508_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceAmbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_ambit', to='licitacions.ambit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_ambit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferencePressupost',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preference_pressupost', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pressupost_min', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('pressupost_max', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceTipusContracte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus_contracte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_tipus_contracte', to='licitacions.tipuscontracte')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_tipus_contracte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.AddConstraint(
            model_name='preferencetipuscontracte',
            constraint=models.UniqueConstraint(fields=('user', 'tipus_contracte'), name='unique_preference_tipus_contracte'),
        ),
        migrations.AddConstraint(
            model_name='preferenceambit',
            constraint=models.UniqueConstraint(fields=('user', 'ambit'), name='unique_preference_ambit'),
        ),
    ]
