# Generated by Django 4.1.7 on 2023-06-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0004_candidatura_estat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='estat',
            field=models.TextField(choices=[('En procés', 'En procés'), ('Rebutjada', 'Rebutjada'), ('Acceptada', 'Acceptada')], default='En procés', max_length=150, null=True),
        ),
    ]
