# Generated by Django 4.1.7 on 2023-03-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0004_licitacioprivada_lloc_execucio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipusContracte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus_contracte', models.CharField(max_length=50)),
                ('subtipus_contracte', models.CharField(max_length=250)),
            ],
            options={
                'unique_together': {('tipus_contracte', 'subtipus_contracte')},
            },
        ),
    ]
