# Generated by Django 4.1.7 on 2023-03-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0006_licitaciopublica_ambit_licitaciopublica_departament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacioprivada',
            name='tipus_contracte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacio_privada', to='licitacions.tipuscontracte'),
        ),
        migrations.AddField(
            model_name='licitaciopublica',
            name='tipus_contracte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacio_publica', to='licitacions.tipuscontracte'),
        ),
    ]
