# Generated by Django 4.1.7 on 2023-05-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
