# Generated by Django 4.1.7 on 2023-04-30 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0003_remove_licitacioprivada_codi_cpv_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('CIF', models.TextField(max_length=9, primary_key=True, serialize=False)),
                ('tipus_id', models.TextField()),
                ('descripcio', models.TextField(null=True)),
                ('cp', models.TextField(null=True)),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('idioma', models.TextField()),
                ('localitzacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licitacions.localitzacio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
