# Generated by Django 4.1.7 on 2023-05-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='CIF',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='descripcio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='idioma',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='localitzacio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipus_id',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
