# Generated by Django 4.1.7 on 2023-04-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='CIF',
            field=models.TextField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefon',
            field=models.TextField(unique=True),
        ),
    ]
