# Generated by Django 4.1.7 on 2023-05-27 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rating_rating_unique_rating'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_rated',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_who_rates',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='value',
        ),
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='user_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
