# Generated by Django 4.1.7 on 2023-06-01 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licitacions', '0002_licitacio_num_favorits_licitacio_visualitzacions'),
        ('users', '0002_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesage', models.CharField(choices=[('Usuario presentado', 'Usuario presentado'), ('Candidatura aceptada', 'Candidatura aceptada'), ('Candidatura rechazada', 'Candidatura rechazada'), ('Licitacion modificada', 'Licitacion modificada'), ('Nueva publicación', 'Nueva publicación')], max_length=150, null=True)),
                ('nom_licitacio', models.CharField(max_length=150, null=True)),
                ('licitacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licitacio_afectada', to='licitacions.licitacio')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
