# Generated by Django 4.1.7 on 2023-05-27 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_rating_unique_rating_remove_rating_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rate',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_to',
        ),
        migrations.AddField(
            model_name='rating',
            name='evaluated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='evaluating_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluating_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
