# Generated by Django 4.1.7 on 2023-05-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow_follow_unique_follow'),
        ('users', '0003_alter_customuser_username'),
    ]

    operations = [
    ]
