# Verion of docker-compose to use 
version: "3.2"

services:
  app:
    build: . #Sets the directory for docker-compose to build.
    volumes: 
      - .:/adjudicat

    ports:
      - "8080:8080"
      
    image: app:adjudicat
    container_name: adjudicat_backend
    command: python manage.py runserver 0.0.0.0:8080 
    
    db:
      image: mysql
      restart: always
      environment:
        MYSQL_DATABASE: 'mysql'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'root'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'adjudicatRoot'
        # Password for root access
        MYSQL_ROOT_PASSWORD: '1234'
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '33060:3306'
      expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
      volumes:
        - my-db:/var/lib/mysql
  # Names our volume
volumes:
  my-db: